apiVersion: parham.my.domain/v1
kind: EmailSenderConfig
metadata:
  labels:
    app.kubernetes.io/name: email-v1
    app.kubernetes.io/managed-by: kustomize
  name: emailsenderconfig-sample
spec:
  # TODO(user): Add fields here
