apiVersion: parham.my.domain/v1
kind: Email
metadata:
  labels:
    app.kubernetes.io/name: email-v1
    app.kubernetes.io/managed-by: kustomize
  name: email-sample
spec:
  senderConfigRef: "emailsenderconfig-sample"
  recipientEmail: "parham.dskn@gmail.com"
  subject: "Test Email"
  body: "This is a test email sent by the operator."

